### ISSUE TITLE
Add support for export of static HTML docs to PDF

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/gh-openapi-docs#21]
Might be as simple as a browser 'print' of the page, but not sure what the effect would be on formatting.

**Comment by jb-adams** [comment]
By 'static HTML docs,' do you mean something akin to what we have for [DRS](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.1.0/docs/) and [RNAget](https://ga4gh-rnaseq.github.io/schema/release/1.0.0)? ie. a less interactive, more traditional looking doc with table of contents? It could be helpful to have this format, and also export it as PDF as you mention.

Also, does this app allow additional sections (front matter, appendices, etc.) to be embedded in the final documentation from Markdown documents (e.g. both `DRS` and `RNAget` docs have preambles and appendices)? If not, are we planning to add that?

**Comment by jaeddy** [comment]
@jb-adams - by 'static HTML docs' I was referring more to the rendered content on GH Pages like [here](https://ga4gh.github.io/workflow-execution-service-schemas/docs/). The emphasis was more on the 'export to PDF' part, which is evidently a requirement for GA4GH SC approval of products. At first glance, a simple 'Print' within the browser seems to work pretty well — but we might want to explore options that give a bit more control over final appearance (e.g., something like pandoc).

As for additional sections, there's actually a lot _more_ flexibility with the new system. I've started putting together a [migration guide](https://github.com/ga4gh/gh-openapi-docs/blob/master/docs/ga4gh-cloud-migration.md) for other GA4GH repos, but will try to address some of those topics more specifically.

**Comment by jb-adams** [comment]
I see, yeah the WES page looks great. Those additional sections (Executive Summary, Introduction), are they written as HTML or MD? Also, are they located in separate files or the OpenAPI yaml?

I'd like to start migrating the specs in other Work Streams (specifically LSG) to using this, I suppose one more thing we need to make sure is working is images. Has anyone tried this?

**Comment by jaeddy** [comment]
> Those additional sections (Executive Summary, Introduction), are they written as HTML or MD? Also, are they located in separate files or the OpenAPI yaml?

Markdown! And they can be embedded or external. The [current spec on `master`](https://github.com/ga4gh/workflow-execution-service-schemas/blob/master/openapi/workflow_execution_service.openapi.yaml) looks like this:

```yaml
  description: >
    ## Executive Summary
    The Workflow Execution Service (WES) API provides ...
    Key features of the API:
    - can request that a workflow be run
    - ...
    ## Introduction
    This document describes the WES API ...
    Use cases include:
    - "Bring your code to the data": ...
    - ...
```

The [updated spec](https://github.com/ga4gh/workflow-execution-service-schemas/blob/reorganize-spec-content/openapi/workflow_execution_service.openapi.yaml) in [this PR](https://github.com/ga4gh/workflow-execution-service-schemas/pull/152) looks like this:

```yaml
tags:
  ...
  - name: Introduction
    description:
      $ref: ./tags/introduction.md
  - name: Authorization & Authentication
    description:
      $ref: ./tags/auth.md
```

I'm a fan of breaking out different sections into a [more granular directory structure](https://github.com/ga4gh/workflow-execution-service-schemas/tree/reorganize-spec-content/openapi), but it's not required if someone wants to maintain a single combined doc.
