### ISSUE TITLE
Add documentation (template?) for TravisCI config

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/gh-openapi-docs#4]
The `.travis.yaml` config for any repo using this package should include a build stage that looks something like this (assuming that the package is published in npm and the Travis integration is appropriately configured):

```yaml
    - stage: build_docs
      language: node_js
      before_script:
      - npm install gh-openapi-docs
      script:
      - "gh-openapi-docs"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        on:
          all_branches: true
```
